### PR TITLE
Getting ready for Modman auto install

### PR DESCRIPTION
**Pull request by Cartrigger**
Literally just adds the repo to core mods and the repos section.

### CODE REVIEW

**Review by gusbunce — APPROVED** [review]
Cart, 
You are an interesting creature. 
However, I will approve this only once.
If it breaks _**ANYTHING**_ I will hunt you down and break every bone in your body, extract the fragments, and feed them to your family.
Have a great day!
Gus

**Comment by Cartrigger** [comment]
Look, the keystore is out of my control... Please dont Gus, my mom still loves me.

**Comment by gusbunce** [comment]
idc

**Comment by Cartrigger** [comment]
**bruh**

**Pull request merged**
